// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_404.ts';
import * as $1 from './routes/_middleware.ts';
import * as $2 from './routes/inspect.ts';
import * as $3 from './routes/inspect/twitch-elements.ts';

const manifest = {
  routes: {
    './routes/_404.ts': $0,
    './routes/_middleware.ts': $1,
    './routes/inspect.ts': $2,
    './routes/inspect/twitch-elements.ts': $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
